[build]
  command = "npm run build"
  publish = "build"
  NODE_ENV = "production"


[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
  NODE_VERSION = "18"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200