const AuthActionTypes = {
	GET_USER_START: "GET_USER_START",
	GET_USER_SUCCESS: "GET_USER_SUCCESS",
	GET_USER_FAIL: "GET_USER_FAIL",

	GET_ONE_STUDENT_START: "GET_ONE_STUDENT_START",
	GET_ONE_STUDENT_SUCCESS: "GET_ONE_STUDENT_SUCCESS",
	GET_ONE_STUDENT_FAIL: "GET_ONE_STUDENT_FAIL",

	GET_ACADEMIC_EXCELLENCE_START: "GET_ACADEMIC_EXCELLENCE_START",
	GET_ACADEMIC_EXCELLENCE_SUCCESS: "GET_ACADEMIC_EXCELLENCE_SUCCESS",
	GET_ACADEMIC_EXCELLENCE_FAIL: "GET_ACADEMIC_EXCELLENCE_FAIL",
};

export default AuthActionTypes;
